config/routes.rb
Rails.application.routes.draw do
  
 
  resources :clients

  resources :users
  resources :profiles
  resources :listings 
   resources :areas
  resources :categories
  

   root 'users#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	attr_accessor :hidden_area_id,:hidden_category_id,:search
	belongs_to :area
	belongs_to :category
	has_and_belongs_to_many :clients
	before_validation :captlize_name, on: [ :create, :update ]
	before_validation :set_area,:set_category	
	validates :listingname, 
			  :presence => true
	validates :price, 
			  :presence => true,
			  :numericality => true		  			  
    validates :area_id, 
	          :presence => {:message => "Please Select any one option!" }
	
	def self.search(search)
	  if search
	  	@area = search
	   self.where("area_id like ?", "#{@area.id}")
	  else
	    self.all
	  end
	end 

	# def self.search(search)
		
	#   if search
	#   	@area = Area.where("areaname like ?", "%#{search}%")	  
	#   else
	#     self.all
	#   end
	# end 



	private

	def captlize_name
		self.listingname = listingname.capitalize if listingname.present?
	end
	def set_area
		self.area_id = self.hidden_area_id if self.hidden_area_id.present?
	end
	def set_category
		self.category_id = self.hidden_category_id if self.hidden_category_id.present?
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
 
  before_action :get_listing, only: [:show,:edit,:update,:destroy]
  before_action :set_area,:set_category, only:[:create,:update]
  before_action :get_area, :get_category
  def index
     @area = Area.search(params[:search]) 
     @listings = Listing.search(@area)
     @listings = [] if @area.blank? && params[:search]
     @listings = Listing.all if params[:search].blank?
     @listing= Listing.new
  end

  def new   
    @listing = Listing.new
  end
  def create
    @listing = Listing.new(set_params)
    rediredcturl = @listing if @listing
    rediredcturl = @area if @area
    rediredcturl = @category if @category
    respond_to do |format|
      if @listing.save            
        format.html { redirect_to rediredcturl, notice: 'Listing was successfully created.' }
        format.json { render :index, status: :created, location: rediredcturl }     
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit    
  end

  def update
     rediredcturl = @listing if @listing
     rediredcturl = @area if @area
     rediredcturl = @category if @category
    respond_to do |format|
      if @listing.update(set_params)      
        format.html { redirect_to rediredcturl, notice: 'Listing was successfully updated.' }
        format.json { render :index, status: :created, location: rediredcturl }    
      else       
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }  
      end
    end
  end

  def destroy   
    reurl = listings_url 
    reurl = @area if @area 
    reurl = @category if @category
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to reurl, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
  end
  end

  private
  def set_params
    params.require(:listing).permit(:listingname,:area_id,:category_id,:contactinfo,:price,:hidden_area_id,:hidden_category_id)
  end
  def get_listing
    @listing = Listing.find(params[:id])
  end
  def set_area
    @area = Area.find(params[:listing][:hidden_area_id]) if params[:listing][:hidden_area_id].present?   
  end
  def set_category
    @category = Category.find(params[:listing][:hidden_category_id]) if params[:listing][:hidden_category_id].present?   
  end
  def get_area
    @area = Area.find(params[:aid]) if params[:aid]
  end
  def get_category
    @category = Category.find(params[:cid]) if params[:cid]
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing   do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
     
        <li><%= message %></li>
       
      <% end %>
      </ul>
    </div>
      
  <% end %>

  <div class="form-group">
    <%= f.label :listingname %><br>
    <%= f.text_field :listingname,:class =>"form-control" %>
  </div>
  <% if !@area %>
   <div class="form-group">
   <%= f.label :area_id, "Select Area" %><br>
   <%= collection_select(:listing, :area_id, Area.all, :id, :areaname, {prompt: true},:class =>"form-control") %>  
  </div>
  <% end %> <% if !@category %>
  <div class="form-group">
  <%= f.label :category_id, "Select Category" %><br>
  <%= collection_select(:listing, :category_id, Category.all, :id, :categoryname, {prompt: true},:class =>"form-control") %>     
  </div>
  <% end %>
   <div class="form-group">
  <%= f.label :price %><br>
  <%= f.text_field :price,:class =>"form-control" %>  
  </div>
   <div class="form-group">
  <%= f.label :contactinfo, "Contact Info" %><br>
  <%= f.text_area :contactinfo,:class =>"form-control" %>  
  </div>
   <%= f.hidden_field :hidden_area_id, :value => "#{@area.id}" if @area %> 
   <%= f.hidden_field :hidden_category_id, :value => "#{@category.id}" if @category %> 
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/listings/destroy.html.erb
<div class="page-header">
  <h1>Listings#destroy</h1>
</div>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<% if @area %>
<%= link_to 'Back',  @area %>
<% elsif @category %>
<%= link_to 'Back',  @category %>
<% else %>
<%= link_to 'Back', listings_path %>
<% end %>

app/views/listings/index.html.erb
<h1>Listings</h1>
<div class="container ">
  
<%= form_tag listings_path, :method => 'get', :class=>"form-inline pull-right" do %>
 <p>
   <div class="form-group">
    <%= text_field_tag :search, params[:search],:class =>"form-control" %>
    </div>
    <%= submit_tag "Search by Area", :name => nil,:class=>"btn btn-warning" %>
  </p>
<% end %> 

</div>
<div class="table-responsive">
 <% if @listings.blank? %>
 <h3>No Results for Search</h3>
 <% else %> 
<table class="table table-hover">  <thead>
    <tr>
      <th>Listing Name</th>
     <th>Area Name</th>
     <th>Category Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.listingname %></td>
        <td><%= listing.area.areaname %></td>
        <td><%= listing.category.categoryname if listing.category.present? %></td>
        <td>
          <%= link_to listing, class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-eye-open"></i>
           <% end %>
           <%= link_to edit_listing_path(listing), class: "btn btn-success" do %>
              <i class="glyphicon glyphicon-edit"></i>
           <% end %>
           <%= link_to listing, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
           <% end %>  
</td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %> 
<div>

<br>
<%= link_to new_listing_path, class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-plus"></i>
           <% end %> 

   
 

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<% if @area %>
<%= link_to 'Back',  @area %>
<% elsif @category %>
<%= link_to 'Back',  @category %>
<% else %>
<%= link_to 'Back', listings_path %>
<% end %>

app/views/listings/show.html.erb
<div class="container-fluid">

<h2>Listing</h2>

<p>
  <strong>Listing Name:</strong>
  <%= @listing.listingname %>
</p>
<p>
  <strong>Area:</strong>
  <%= @listing.area.areaname %>
</p>
<p>
  <strong>Category:</strong>
  <%= @listing.category.categoryname if @listing.category.present? %>
</p>
<p>
  <strong>Price:</strong>
  <%= number_to_currency(@listing.price, unit: 'rs',format: '%n%u') %>
</p>
<p>
  <strong>Contact Info:</strong>
  <%= @listing.contactinfo %>
</p>

<%= link_to 'Edit', edit_listing_path,:class => "btn btn-default" %>
<%= link_to 'Back', listings_path,:class => "btn btn-default" %>
</div>