config/routes.rb
Rails.application.routes.draw do
  
 
  resources :clients

  resources :users
  resources :profiles
  resources :listings 
   resources :areas
  resources :categories
  

   root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile, dependent: :destroy
	before_validation :captlize_name, on: [ :create, :update ]
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username, 
			  :presence => true,
			  :uniqueness => true
    validates :email, 
	          :presence => {:message => "Enter your email address!" },
	          :format => { :with => VALID_EMAIL_REGEX, :message => "Enter a valid Email address !"},
	          :uniqueness => {:case_sensitive => false, :message => "Email already exists!"}
	private

	def captlize_name
		self.username = username.capitalize if username.present?
	end          
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
     
        <li><%= message %></li>
       
      <% end %>
      </ul>
    </div>
      
  <% end %>

  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<div class="table-responsive">
<table class="table table-hover">  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.username}", user%></td>
        <td><%= user.email %></td>
        <td>
        <%= link_to 'Edit', edit_user_path(user), {:class => "btn btn-success icon-search"} %>
        <%= link_to 'Delete', user, :class => 'btn btn-danger icon-search', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>

<br>

 <%= link_to(new_user_path, :class => 'btn btn-primary') do %>
          New User <span class="icon-search"></span>
      <% end %>     
 

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :class => "btn btn-default" %>

app/views/users/show.html.erb
<div class="container-fluid">

<h2>User  Profile</h2>
<% if @user.profile.present? %> 
<p>
  <strong>First Name:</strong>
  <%= @user.profile.fname %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.profile.lname %>
</p>
 <p>
 <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
 <strong>Profile Picture:</strong>
  <%= image_tag @user.profile.pic.url(:thumb) %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Phone No:</strong>
  <%= @user.profile.phoneno %>
</p>
<p>
  <strong>Date Of Birth:</strong>
  <%= @user.profile.dob %>
</p>
<p>
  <strong>Age:</strong>
  <%= time_ago_in_words(@user.profile.dob) %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @user.profile.gender %>
</p>
<p>
  <strong>Likes:</strong>
  <%= @user.profile.likes %>
</p>
<p>
  <strong>Address:</strong>
  <%= @user.profile.address %>
</p>
<%= link_to 'Edit Profile', edit_profile_path,:class => "btn btn-primary" %>
  <% else  %>
   <p>
 <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
  <p>No Profile is set <%= link_to 'Click to Set Profile', new_profile_path(:uid => @user.id) %></p>


 <% end  %>
<%= link_to 'Back', users_path,:class => "btn btn-default" %>
</div>