config/routes.rb
Rails.application.routes.draw do
  
 
  resources :clients

  resources :users
  resources :profiles
  resources :listings 
   resources :areas
  resources :categories
  

   root 'users#index'

end

app/models/area.rb
class Area < ActiveRecord::Base	
	has_many :listings, dependent: :destroy
	before_validation :captlize_name, on: [ :create, :update ]
	validates :areaname, 
			  :presence => true,
			  :uniqueness => true
    validates :position,
   			  :numericality => {:message => "is not a number." }, 
	          :presence => true,	         
	          :uniqueness => {:message => "Position already exists!"}

	def self.search(search)
	  if search
	    self.where(areaname: "#{search}").take	 
	  end
	end 

	private

	def captlize_name
		self.areaname = areaname.capitalize if areaname.present?
	end            
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController 
  before_action :set_area ,only: [:show,:update,:destroy,:edit]
  def index
    @areas = Area.order("position ASC")
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(set_params)
    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @area.update(set_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_params
    params.require(:area).permit(:areaname, :position)
  end
  def set_area
      @area = Area.find(params[:id])
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
     
        <li><%= message %></li>
       
      <% end %>
      </ul>
    </div>
      
  <% end %>

  <div class="form-group">
    <%= f.label :areaname %><br>
    <%= f.text_field :areaname,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/areas/destroy.html.erb
<div class="page-header">
  <h1>Areas#destroy</h1>
</div>
<p>Find me in app/views/areas/destroy.html.erb</p>

app/views/areas/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing Areas</h1>
<div class="table-responsive">
<table class="table table-hover">  <thead>
    <tr>
      <th>Areaname</th>
      <th>ListingsCount</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to "#{area.areaname}", area %></td>
        <td><%= area.listings.size if area.listings %></td>
        <td><%= area.position %></td>
        <td>
           <%= link_to edit_area_path(area), class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-edit"></i>
           <% end %>
           <%= link_to area, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
           <% end %>       
      </tr>
    <% end %>
  </tbody>
</table>
<div>

<br>
 
   <%= link_to new_area_path, class: "btn btn-primary" do %>
    <i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path, :class => "btn btn-default" %>

app/views/areas/show.html.erb
<div class="container-fluid">

<h2> <%= @area.areaname %> Listings</h2>

<div class="table-responsive">
  <% if @area.listings.blank? %>
 <p>No more listings belongs to this area</p>
  <p>Click Plus to add Listings....</p>
 <% else %> 
<table class="table table-hover">  <thead>
    <tr>
      <th>Listing Name</th>
     <th>Area Name</th>
     <th>Category Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @area.listings.each do |listing| %>
      <tr>
        <td><%= listing.listingname %></td> 
        <td><%= @area.areaname %></td>      
        <td><%= listing.category.categoryname if listing.category.present? %></td>
        <td>  
        <%= link_to edit_listing_path(listing,:aid => @area.id), class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-edit"></i>
           <% end %>
           <%= link_to listing_path(listing,:aid => @area.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
              <% end %>     
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div>
<%= link_to new_listing_path({:aid => @area.id}), class: "btn btn-primary" do %>
    <i class="glyphicon glyphicon-plus"></i>
<% end %>
<%= link_to areas_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-arrow-left"></i>
<% end %>