config/routes.rb
Rails.application.routes.draw do
  
 
  resources :clients

  resources :users
  resources :profiles
  resources :listings 
   resources :areas
  resources :categories
  

   root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :listings
	before_validation :captlize_name, on: [ :create, :update ]
	validates :categoryname, 
			  :presence => true,
			  :uniqueness => true
    validates :position,
   			  :numericality => {:message => "is not a number." }, 
	          :presence => true,	         
	          :uniqueness => {:message => "Position already exists!"}

	private

	def captlize_name
		self.categoryname = categoryname.capitalize if categoryname.present?
	end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :get_categoty, only: [:show,:edit,:update,:destroy]
  def index
    @categories = Category.order("position ASC")
  end

  def new
    @category = Category.new
  end

  def create
   @category = Category.new(set_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end 
  end

  def show
  end

  def edit
  end

  def update 
    respond_to do |format|
      if @category.update(set_params)
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end  
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def get_categoty
    @category = Category.find(params[:id])
  end
  def set_params
    params.require(:category).permit(:categoryname,:position)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
     
        <li><%= message %></li>
       
      <% end %>
      </ul>
    </div>
      
  <% end %>

  <div class="form-group">
    <%= f.label :categoryname %><br>
    <%= f.text_field :categoryname,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/categories/destroy.html.erb
<div class="page-header">
  <h1>Categories#destroy</h1>
</div>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>
<div class="table-responsive">
<table class="table table-hover">  <thead>
    <tr>
      <th>CategoryName</th>
       <th>ListingsCount</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to "#{category.categoryname}", category%></td>
        <td><%= category.listings.size if category.listings %></td>
        <td><%= category.position %></td>
        <td>
        <%= link_to 'Edit', edit_category_path(category), {:class => "btn btn-success icon-search"} %>
        <%= link_to 'Delete', category, :class => 'btn btn-danger icon-search', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>

<br>

 <%= link_to(new_category_path, :class => 'btn btn-primary') do %>
          New category <span class="icon-search"></span>
      <% end %>     
 

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path, :class => "btn btn-default" %>

app/views/categories/show.html.erb
<div class="container-fluid">

<h2> <%= @category.categoryname %> Listings</h2>

<div class="table-responsive">
<table class="table table-hover">  <thead>
    <tr>
      <th>Listing Name</th>
     <th>Category Name</th>
     <th>Area Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.listings.each do |listing| %>
      <tr>
        <td><%= listing.listingname %></td> 
        <td><%= @category.categoryname %></td>      
        <td><%= listing.area.areaname if listing.area.present? %></td>
        <td>
      
        <%= link_to 'Edit', edit_listing_path(listing,:cid => @category.id), {:class => "btn btn-success icon-search"} %>
        <%= link_to 'Delete', listing_path(listing,:cid => @category.id), :class => 'btn btn-danger icon-search', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>

<%= link_to 'New Listing', new_listing_path({:cid => @category.id}),:class => "btn btn-primary" %>
<%= link_to 'Back', categories_path,:class => "btn btn-default" %>
</div>